// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Space.Data;
using System;

namespace Space.Data.Migrations
{
    [DbContext(typeof(SpaceContext))]
    partial class SpaceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Space.Domain.Ravioli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ExpiryDate");

                    b.Property<DateTime>("PackDate");

                    b.Property<int?>("SpaceshipId");

                    b.HasKey("Id");

                    b.HasIndex("SpaceshipId");

                    b.ToTable("Ravioli");
                });

            modelBuilder.Entity("Space.Domain.Spaceship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Spaceships");
                });

            modelBuilder.Entity("Space.Domain.Ravioli", b =>
                {
                    b.HasOne("Space.Domain.Spaceship")
                        .WithMany("Ravioli")
                        .HasForeignKey("SpaceshipId");
                });
#pragma warning restore 612, 618
        }
    }
}
